version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "deps"
    labels:
      - "t-dependencies"
