version: v1

labels:
  - label: c-cache
    sync: true
    matcher:
      files: "model/src/cache/**/*"

  - label: c-dependencies
    matcher:
      files: "Cargo.lock"
      title: "^deps(\\(.+\\))?!?: .*"

  - label: c-event
    sync: true
    matcher:
      files: "raidprotect/src/event/**/*"

  - label: c-interaction
    sync: true
    matcher:
      files: "raidprotect/src/interaction/**/*"

  - label: c-model
    sync: true
    matcher:
      files:
        all: ["model/**/*", "!model/src/cache/**/*"]

  - label: c-translations
    sync: true
    matcher:
      files: "raidprotect/locales/**/*"

  - label: c-web
    sync: true
    matchers:
      files: "web/**/*"

  - label: t-fix
    matcher:
      title: "^fix(\\(.+\\))?!?: .*"

  - label: t-feature
    matcher:
      title: "^feat(\\(.+\\))?!?: .*"

  - label: t-enhancement
    matcher:
      title: "^enhancement(\\(.+\\))?!?: .*"

  - label: t-chore
    matcher:
      title: "^chore(\\(.+\\))?!?: .*"

  - label: t-refactor
    matcher:
      title: "^refactor(\\(.+\\))?!?: .*"

  - label: t-actions
    matcher:
      title: "^ci(\\(.+\\))?!?: .*"
