tasks:
  - before: rustup component add clippy
  - init: cargo build

vscode:
  extensions:
    - editorconfig.editorconfig
    - matklad.rust-analyzer
    - bungcip.better-toml
    - eamodio.gitlens
