image: gitpod/workspace-mongodb

tasks:
  - init: mkdir -p /workspace/data
    command: mongod --dbpath /workspace/data

  - init: sleep 10 && cargo doc
    command: npx -qy http-server target/doc/ -p 8080

  - before: rustup component add clippy
    init: cargo build

ports:
  - port: 8080
    visibility: private
    onOpen: notify

github:
  prebuilds:
    master: true
    pullRequests: true
    addCheck: false

vscode:
  extensions:
    - matklad.rust-analyzer
    - editorconfig.editorconfig
    - tamasfe.even-better-toml
    - serayuzgur.crates
    - eamodio.gitlens
    - Lokalise.i18n-ally
