tasks:
  - before: rustup install stable --profile default && rustup default stable
  - init: cargo build

vscode:
  extensions:
    - editorconfig.editorconfig
    - matklad.rust-analyzer
    - bungcip.better-toml
    - eamodio.gitlens
