tasks:
  - before: rustup component add clippy
    init: cargo build

  - init: cargo doc
    command: npx -qy http-server target/doc/ -p 8080

ports:
  - port: 8080
    visibility: private
    onOpen: notify

github:
  prebuilds:
    master: true
    pullRequests: true
    addCheck: true

vscode:
  extensions:
    - editorconfig.editorconfig
    - matklad.rust-analyzer
    - bungcip.better-toml
    - serayuzgur.crates
    - eamodio.gitlens
