[package]
name = "raidprotect"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raidprotect-gateway = { path = "../gateway" }
raidprotect-util = { path = "../util" }

anyhow = "1"
dotenv = "0.15"
envy = "0.4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1" }
