[package]
name = "raidprotect"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raidprotect-model = { path = "../model" }

anyhow = { version = "1.0.58", features = ["backtrace"] }
async-trait = "0.1.56"
nanoid = "0.4.0"
once_cell = "1.13.0"
rosetta-i18n = "0.1.2"

# Tokio ecosystem
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
tracing = "0.1.35"

# Twilight
twilight-gateway = "0.11.1"
twilight-http = "0.11.1"
twilight-interactions = "0.11.0"
twilight-mention = "0.11.1"
twilight-model = "0.11.1"
twilight-util = { version = "0.11.1", features = ["builder", "snowflake"] }

# Message parsing
any_ascii = "0.3.1"
linkify = "0.8.1"
unicode-segmentation = "1.9.0"
url = "2.2.2"

[build-dependencies]
rosetta-build = "0.1.2"
