[package]
name = "raidprotect"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raidprotect-model = { path = "../model" }
raidprotect-translations = { path = "../translations" }

anyhow = "1"
async-trait = "0.1"
nanoid = "0.4"
once_cell = "1.12"
thiserror = "1"

# Tokio ecosystem
futures = "0.3"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
tracing = { version = "0.1" }
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["std", "fmt", "ansi"], default-features = false }

# Twilight
twilight-gateway = "0.11"
twilight-http = "0.11"
twilight-interactions = "0.11"
twilight-mention = "0.11"
twilight-model = "0.11"
twilight-util = { version = "0.11", features = ["builder", "snowflake"] }
twilight-validate = "0.11"

# Configuration
envy = "0.4"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }

# Message parsing
any_ascii = "0.3"
linkify = "0.8"
unicode-segmentation = "1.9"
url = "2.2"
